package com.equabli.collectprism.util;

import com.equabli.domain.entity.ConfRecordStatus;

public class DBQueryUtils {
    //--------QUERY GET DATA SUSPECTED DETAIL-----
    public static final String GET_CHANGE_LOG_SUSPECTED_DETAIL = new StringBuffer()
            .append("	select case when (el.value ->> 'key'::text)='e' then err.short_name else CONCAT('W', SUBSTRING(err.short_name,2)) end shortName, err.description, count(1)  ")
            .append("	from data.changelog cl  ")
            .append("	inner join data.account acc ON acc.client_id = cl.client_id and acc.client_account_number = cl.client_account_number ")
            .append("	CROSS JOIN LATERAL json_array_elements(cl.err_code_json::json) el(value) ")
            .append("	JOIN conf.errwarmessage err ON (el.value ->> 'value'::text) = err.short_name::text ")
            .append("	where (:clientId::integer is null or cl.client_id = :clientId::integer) and cl.record_status_id = :suspectedRecordStatusId ")
            .append("	AND (:clientJobScheduleId::bigint is null or acc.client_job_schedule_id = :clientJobScheduleId::bigint) ")
            .append("	AND coalesce(date(cl.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(cl.dtm_utc_create), current_date)  ")
            .append("	AND coalesce(date(cl.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(cl.dtm_utc_create), current_date) ")
            .append("	GROUP BY shortName, err.description ")
            .toString();

    public static final String GET_PAYMENT_PLAN_SUSPECTED_DETAIL = new StringBuffer()
            .append("	select case when (el.value ->> 'key'::text)='e' then err.short_name else CONCAT('W', SUBSTRING(err.short_name,2)) end shortName, err.description, count(1)  ")
            .append("	from data.payment_plan cl  ")
            .append("	inner join data.account acc ON acc.client_id = cl.client_id and acc.client_account_number = cl.client_account_number ")
            .append("	CROSS JOIN LATERAL json_array_elements(cl.err_code_json::json) el(value) ")
            .append("	JOIN conf.errwarmessage err ON (el.value ->> 'value'::text) = err.short_name::text ")
            .append("	where (:clientId::integer is null or cl.client_id = :clientId::integer) and cl.record_status_id = :suspectedRecordStatusId ")
            .append("	AND (:clientJobScheduleId::bigint is null or acc.client_job_schedule_id = :clientJobScheduleId::bigint) ")
            .append("	AND coalesce(date(cl.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(cl.dtm_utc_create), current_date)  ")
            .append("	AND coalesce(date(cl.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(cl.dtm_utc_create), current_date) ")
            .append("	GROUP BY shortName, err.description ")
            .toString();

    public static final String GET_EMPLOYER_SUSPECTED_DETAIL = new StringBuffer()
            .append("	select case when (el.value ->> 'key'::text)='e' then err.short_name else CONCAT('W', SUBSTRING(err.short_name,2)) end shortName, err.description, count(1)  ")
            .append("	from data.employer cl  ")
            .append("	inner join data.account acc ON acc.client_id = cl.client_id and acc.client_account_number = cl.client_account_number ")
            .append("	CROSS JOIN LATERAL json_array_elements(cl.err_code_json::json) el(value) ")
            .append("	JOIN conf.errwarmessage err ON (el.value ->> 'value'::text) = err.short_name::text ")
            .append("	where (:clientId::integer is null or cl.client_id = :clientId::integer) and cl.record_status_id = :suspectedRecordStatusId ")
            .append("	AND (:clientJobScheduleId::bigint is null or acc.client_job_schedule_id = :clientJobScheduleId::bigint) ")
            .append("	AND coalesce(date(cl.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(cl.dtm_utc_create), current_date)  ")
            .append("	AND coalesce(date(cl.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(cl.dtm_utc_create), current_date) ")
            .append("	GROUP BY shortName, err.description ")
            .toString();

    public static final String GET_COMPLIANCE_SUSPECTED_DETAIL = new StringBuffer()
            .append("	select case when (el.value ->> 'key'::text)='e' then err.short_name else CONCAT('W', SUBSTRING(err.short_name,2)) end shortName, err.description, count(1)  ")
            .append("	from data.compliance cl  ")
            .append("	inner join data.account acc ON acc.client_id = cl.client_id and acc.client_account_number = cl.client_account_number ")
            .append("	CROSS JOIN LATERAL json_array_elements(cl.err_code_json::json) el(value) ")
            .append("	JOIN conf.errwarmessage err ON (el.value ->> 'value'::text) = err.short_name::text ")
            .append("	where (:clientId::integer is null or cl.client_id = :clientId::integer) and cl.record_status_id = :suspectedRecordStatusId ")
            .append("	AND (:clientJobScheduleId::bigint is null or acc.client_job_schedule_id = :clientJobScheduleId::bigint) ")
            .append("	AND coalesce(date(cl.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(cl.dtm_utc_create), current_date)  ")
            .append("	AND coalesce(date(cl.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(cl.dtm_utc_create), current_date) ")
            .append("	GROUP BY shortName, err.description ")
            .toString();

    public static final String GET_CHARGE_OFF_ACCOUNT_SUSPECTED_DETAIL = new StringBuffer()
            .append("	select case when (el.value ->> 'key'::text)='e' then err.short_name else CONCAT('W', SUBSTRING(err.short_name,2)) end shortName, err.description, count(1)  ")
            .append("	from data.chargeoff_account cl  ")
            .append("	inner join data.account acc ON acc.client_id = cl.client_id and acc.client_account_number = cl.client_account_number ")
            .append("	CROSS JOIN LATERAL json_array_elements(cl.err_code_json::json) el(value) ")
            .append("	JOIN conf.errwarmessage err ON (el.value ->> 'value'::text) = err.short_name::text ")
            .append("	where (:clientId::integer is null or cl.client_id = :clientId::integer) and cl.record_status_id = :suspectedRecordStatusId ")
            .append("	AND (:clientJobScheduleId::bigint is null or acc.client_job_schedule_id = :clientJobScheduleId::bigint) ")
            .append("	AND coalesce(date(cl.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(cl.dtm_utc_create), current_date)  ")
            .append("	AND coalesce(date(cl.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(cl.dtm_utc_create), current_date) ")
            .append("	GROUP BY shortName, err.description ")
            .toString();

    public static final String GET_ACCOUNT_TAG_SUSPECTED_DETAIL = new StringBuffer()
            .append("	select case when (el.value ->> 'key'::text)='e' then err.short_name else CONCAT('W', SUBSTRING(err.short_name,2)) end shortName, err.description, count(1)  ")
            .append("	from data.account_tag cl  ")
            .append("	inner join data.account acc ON acc.client_id = cl.client_id and acc.client_account_number = cl.client_account_number ")
            .append("	CROSS JOIN LATERAL json_array_elements(cl.err_code_json::json) el(value) ")
            .append("	JOIN conf.errwarmessage err ON (el.value ->> 'value'::text) = err.short_name::text ")
            .append("	where (:clientId::integer is null or cl.client_id = :clientId::integer) and cl.record_status_id = :suspectedRecordStatusId ")
            .append("	AND (:clientJobScheduleId::bigint is null or acc.client_job_schedule_id = :clientJobScheduleId::bigint) ")
            .append("	AND coalesce(date(cl.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(cl.dtm_utc_create), current_date)  ")
            .append("	AND coalesce(date(cl.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(cl.dtm_utc_create), current_date) ")
            .append("	GROUP BY shortName, err.description ")
            .toString();

    public static final String GET_CHAIN_OF_TITLE_SUSPECTED_DETAIL = new StringBuffer()
            .append("	select case when (el.value ->> 'key'::text)='e' then err.short_name else CONCAT('W', SUBSTRING(err.short_name,2)) end shortName, err.description, count(1)  ")
            .append("	from data.chainoftitle cl  ")
            .append("	inner join data.account acc ON acc.client_id = cl.client_id and acc.client_account_number = cl.client_account_number ")
            .append("	CROSS JOIN LATERAL json_array_elements(cl.err_code_json::json) el(value) ")
            .append("	JOIN conf.errwarmessage err ON (el.value ->> 'value'::text) = err.short_name::text ")
            .append("	where (:clientId::integer is null or cl.client_id = :clientId::integer) and cl.record_status_id = :suspectedRecordStatusId ")
            .append("	AND (:clientJobScheduleId::bigint is null or acc.client_job_schedule_id = :clientJobScheduleId::bigint) ")
            .append("	AND coalesce(date(cl.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(cl.dtm_utc_create), current_date)  ")
            .append("	AND coalesce(date(cl.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(cl.dtm_utc_create), current_date) ")
            .append("	GROUP BY shortName, err.description ")
            .toString();

    public static final String GET_COMMUNICATION_SUSPECTED_DETAIL = new StringBuffer()
            .append("	select case when (el.value ->> 'key'::text)='e' then err.short_name else CONCAT('W', SUBSTRING(err.short_name,2)) end shortName, err.description, count(1)  ")
            .append("	from data.communication_detail cl  ")
            .append("	inner join data.account acc ON acc.client_id = cl.client_id and acc.client_account_number = cl.client_account_number ")
            .append("	CROSS JOIN LATERAL json_array_elements(cl.err_code_json::json) el(value) ")
            .append("	JOIN conf.errwarmessage err ON (el.value ->> 'value'::text) = err.short_name::text ")
            .append("	where (:clientId::integer is null or cl.client_id = :clientId::integer) and cl.record_status_id = :suspectedRecordStatusId ")
            .append("	AND (:clientJobScheduleId::bigint is null or acc.client_job_schedule_id = :clientJobScheduleId::bigint) ")
            .append("	AND coalesce(date(cl.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(cl.dtm_utc_create), current_date)  ")
            .append("	AND coalesce(date(cl.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(cl.dtm_utc_create), current_date) ")
            .append("	GROUP BY shortName, err.description ")
            .toString();

    public static final String GET_LEGAL_SUSPECTED_DETAIL = new StringBuffer()
            .append(" select case when (el.value ->> 'key'::text)='e' then err.short_name else CONCAT('W', SUBSTRING(err.short_name,2)) end shortName, err.description, count(1) ")
            .append(" from data.legal_placement lp ")
            .append(" inner join data.account acc ON acc.client_id = lp.client_id and acc.client_account_number = lp.client_account_number ")
            .append(" CROSS JOIN LATERAL json_array_elements(lp.err_code_json::json) el(value) ")
            .append(" JOIN conf.errwarmessage err ON (el.value ->> 'value'::text) = err.short_name::text ")
            .append(" where (:clientId::integer is null or lp.client_id = :clientId::integer) and lp.record_status_id = :suspectedRecordStatusId ")
            .append(" AND (:clientJobScheduleId::bigint is null or acc.client_job_schedule_id = :clientJobScheduleId::bigint) ")
            .append(" AND coalesce(date(lp.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(lp.dtm_utc_create), current_date) ")
            .append(" AND coalesce(date(lp.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(lp.dtm_utc_create), current_date) ")
            .append(" GROUP BY shortName, err.description ")
            .toString();

    public static final String GET_LIEN_SUSPECTED_DETAIL = new StringBuffer()
            .append("	select case when (el.value ->> 'key'::text)='e' then err.short_name else CONCAT('W', SUBSTRING(err.short_name,2)) end shortName, err.description, count(1)  ")
            .append("	from data.legal_lien cl  ")
            .append("	inner join data.account acc ON acc.client_id = cl.client_id and acc.client_account_number = cl.client_account_number ")
            .append("	CROSS JOIN LATERAL json_array_elements(cl.err_code_json::json) el(value) ")
            .append("	JOIN conf.errwarmessage err ON (el.value ->> 'value'::text) = err.short_name::text ")
            .append("	where (:clientId::integer is null or cl.client_id = :clientId::integer) and cl.record_status_id = :suspectedRecordStatusId ")
            .append("	AND (:clientJobScheduleId::bigint is null or acc.client_job_schedule_id = :clientJobScheduleId::bigint) ")
            .append("	AND coalesce(date(cl.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(cl.dtm_utc_create), current_date)  ")
            .append("	AND coalesce(date(cl.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(cl.dtm_utc_create), current_date) ")
            .append("	GROUP BY shortName, err.description ")
            .toString();

    public static final String GET_GARNISHMENT_SUSPECTED_DETAIL = new StringBuffer()
            .append("	select case when (el.value ->> 'key'::text)='e' then err.short_name else CONCAT('W', SUBSTRING(err.short_name,2)) end shortName, err.description, count(1)  ")
            .append("	from data.legal_garnishment cl  ")
            .append("	inner join data.account acc ON acc.client_id = cl.client_id and acc.client_account_number = cl.client_account_number ")
            .append("	CROSS JOIN LATERAL json_array_elements(cl.err_code_json::json) el(value) ")
            .append("	JOIN conf.errwarmessage err ON (el.value ->> 'value'::text) = err.short_name::text ")
            .append("	where (:clientId::integer is null or cl.client_id = :clientId::integer) and cl.record_status_id = :suspectedRecordStatusId ")
            .append("	AND (:clientJobScheduleId::bigint is null or acc.client_job_schedule_id = :clientJobScheduleId::bigint) ")
            .append("	AND coalesce(date(cl.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(cl.dtm_utc_create), current_date)  ")
            .append("	AND coalesce(date(cl.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(cl.dtm_utc_create), current_date) ")
            .append("	GROUP BY shortName, err.description ")
            .toString();

    public static final String GET_BANKRUPTCY_SUSPECTED_DETAIL = new StringBuffer()
            .append(" SELECT case when (el.value ->> 'key'::text)='e' then err.short_name else CONCAT('W', SUBSTRING(err.short_name,2)) end shortName, err.description, count(1) ")
            .append(" FROM data.bankruptcy b ")
            .append(" INNER JOIN data.account acc ON acc.client_id = b.client_id and acc.client_account_number = b.client_account_number ")
            .append(" CROSS JOIN LATERAL json_array_elements(b.err_code_json::json) el(value) ")
            .append(" JOIN conf.errwarmessage err ON (el.value ->> 'value'::text) = err.short_name::text ")
            .append(" WHERE (:clientId::integer is null or b.client_id = :clientId::integer) and b.record_status_id = :suspectedRecordStatusId ")
            .append(" AND (:clientJobScheduleId::bigint is null or acc.client_job_schedule_id = :clientJobScheduleId::bigint) ")
            .append(" AND coalesce(date(b.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(b.dtm_utc_create), current_date) ")
            .append(" AND coalesce(date(b.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(b.dtm_utc_create), current_date) ")
            .append(" GROUP BY shortName, err.description ")
            .toString();

    public static final String GET_COMPLAINT_SUSPECTED_DETAIL = new StringBuffer()
            .append(" SELECT case when (el.value ->> 'key'::text)='e' then err.short_name else CONCAT('W', SUBSTRING(err.short_name,2)) end shortName, err.description, count(1) ")
            .append(" FROM data.complaint c ")
            .append(" INNER JOIN data.account acc ON acc.client_id = c.client_id and acc.client_account_number = c.client_account_number ")
            .append(" CROSS JOIN LATERAL json_array_elements(c.err_code_json::json) el(value) ")
            .append(" JOIN conf.errwarmessage err ON (el.value ->> 'value'::text) = err.short_name::text ")
            .append(" WHERE (:clientId::integer is null or c.client_id = :clientId::integer) and c.record_status_id = :suspectedRecordStatusId ")
            .append(" AND (:clientJobScheduleId::bigint is null or acc.client_job_schedule_id = :clientJobScheduleId::bigint) ")
            .append(" AND coalesce(date(c.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(c.dtm_utc_create), current_date) ")
            .append(" AND coalesce(date(c.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(c.dtm_utc_create), current_date) ")
            .append(" GROUP BY shortName, err.description ")
            .toString();

    public static final String GET_DISPUTE_SUSPECTED_DETAIL = new StringBuffer()
            .append(" SELECT case when (el.value ->> 'key'::text)='e' then err.short_name else CONCAT('W', SUBSTRING(err.short_name,2)) end shortName, err.description, count(1) ")
            .append(" FROM data.dispute d ")
            .append(" INNER JOIN data.account acc ON acc.client_id = d.client_id and acc.client_account_number = d.client_account_number ")
            .append(" CROSS JOIN LATERAL json_array_elements(d.err_code_json::json) el(value) ")
            .append(" JOIN conf.errwarmessage err ON (el.value ->> 'value'::text) = err.short_name::text ")
            .append(" WHERE (:clientId::integer is null or d.client_id = :clientId::integer) and d.record_status_id = :suspectedRecordStatusId ")
            .append(" AND (:clientJobScheduleId::bigint is null or acc.client_job_schedule_id = :clientJobScheduleId::bigint) ")
            .append(" AND coalesce(date(d.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(d.dtm_utc_create), current_date) ")
            .append(" AND coalesce(date(d.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(d.dtm_utc_create), current_date) ")
            .append(" GROUP BY shortName, err.description ")
            .toString();

    //--------QUERY GET DATA DETAIL FOR_SUSPECTED-----
    public static final String GET_CHANGE_LOG_DETAIL_FOR_SUSPECTED = new StringBuffer()
            .append("	select cl.changelog_id changelogId, cl.client_id clientId, cl.client_account_number clientAccountNumber ")
            .append("	from data.changelog cl  ")
            .append("	inner join data.account acc ON acc.client_id = cl.client_id and acc.client_account_number = cl.client_account_number ")
            .append("	CROSS JOIN LATERAL json_array_elements(cl.err_code_json::json) el(value) ")
            .append("	JOIN conf.errwarmessage err ON (el.value ->> 'key'::text) = :code and (el.value ->> 'value'::text) = :codeType  ")
            .append("	where (:clientId::integer is null or cl.client_id = :clientId::integer) and cl.record_status_id = :suspectedRecordStatusId ")
            .append("	AND (:clientJobScheduleId::bigint is null or acc.client_job_schedule_id = :clientJobScheduleId::bigint) ")
            .append("	AND coalesce(date(cl.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(cl.dtm_utc_create), current_date)  ")
            .append("	AND coalesce(date(cl.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(cl.dtm_utc_create), current_date) ")
            .append("	group by cl.changelog_id, cl.client_id, cl.client_account_number ")
            .toString();

    public static final String GET_PAYMENT_PLAN_DETAIL_FOR_SUSPECTED = new StringBuffer()
            .append("	select cl.payment_plan_id paymentPlanId, cl.client_id clientId, cl.client_account_number clientAccountNumber ")
            .append("	from data.payment_plan cl  ")
            .append("	inner join data.account acc ON acc.client_id = cl.client_id and acc.client_account_number = cl.client_account_number ")
            .append("	CROSS JOIN LATERAL json_array_elements(cl.err_code_json::json) el(value) ")
            .append("	JOIN conf.errwarmessage err ON (el.value ->> 'key'::text) = :code and (el.value ->> 'value'::text) = :codeType ")
            .append("	where (:clientId::integer is null or cl.client_id = :clientId::integer) and cl.record_status_id = :suspectedRecordStatusId ")
            .append("	AND (:clientJobScheduleId::bigint is null or acc.client_job_schedule_id = :clientJobScheduleId::bigint) ")
            .append("	AND coalesce(date(cl.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(cl.dtm_utc_create), current_date)  ")
            .append("	AND coalesce(date(cl.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(cl.dtm_utc_create), current_date) ")
            .append("	group by cl.payment_plan_id, cl.client_id, cl.client_account_number ")
            .toString();

    public static final String GET_EMPLOYER_DETAIL_FOR_SUSPECTED = new StringBuffer()
            .append("	select cl.employer_id employerId, cl.client_id clientId, cl.client_account_number clientAccountNumber ")
            .append("	from data.employer cl  ")
            .append("	inner join data.account acc ON acc.client_id = cl.client_id and acc.client_account_number = cl.client_account_number ")
            .append("	CROSS JOIN LATERAL json_array_elements(cl.err_code_json::json) el(value) ")
            .append("	JOIN conf.errwarmessage err ON (el.value ->> 'key'::text) = :code and (el.value ->> 'value'::text) = :codeType ")
            .append("	where (:clientId::integer is null or cl.client_id = :clientId::integer) and cl.record_status_id = :suspectedRecordStatusId ")
            .append("	AND (:clientJobScheduleId::bigint is null or acc.client_job_schedule_id = :clientJobScheduleId::bigint) ")
            .append("	AND coalesce(date(cl.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(cl.dtm_utc_create), current_date)  ")
            .append("	AND coalesce(date(cl.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(cl.dtm_utc_create), current_date) ")
            .append("	group by cl.employer_id, cl.client_id, cl.client_account_number ")
            .toString();

    public static final String GET_COMPLIANCE_DETAIL_FOR_SUSPECTED = new StringBuffer()
            .append("	select cl.compliance_id complianceId, cl.client_id clientId, cl.client_account_number clientAccountNumber ")
            .append("	from data.compliance cl  ")
            .append("	inner join data.account acc ON acc.client_id = cl.client_id and acc.client_account_number = cl.client_account_number ")
            .append("	CROSS JOIN LATERAL json_array_elements(cl.err_code_json::json) el(value) ")
            .append("	JOIN conf.errwarmessage err ON (el.value ->> 'key'::text) = :code and (el.value ->> 'value'::text) = :codeType ")
            .append("	where (:clientId::integer is null or cl.client_id = :clientId::integer) and cl.record_status_id = :suspectedRecordStatusId ")
            .append("	AND (:clientJobScheduleId::bigint is null or acc.client_job_schedule_id = :clientJobScheduleId::bigint) ")
            .append("	AND coalesce(date(cl.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(cl.dtm_utc_create), current_date)  ")
            .append("	AND coalesce(date(cl.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(cl.dtm_utc_create), current_date) ")
            .append("	group by cl.compliance_id, cl.client_id, cl.client_account_number ")
            .toString();

    public static final String GET_CHARGE_OFF_ACCOUNT_DETAIL_FOR_SUSPECTED = new StringBuffer()
            .append("	select cl.chargeoff_account_id chargeoffAccountId, cl.client_id clientId, cl.client_account_number clientAccountNumber ")
            .append("	from data.chargeoff_account cl  ")
            .append("	inner join data.account acc ON acc.client_id = cl.client_id and acc.client_account_number = cl.client_account_number ")
            .append("	CROSS JOIN LATERAL json_array_elements(cl.err_code_json::json) el(value) ")
            .append("	JOIN conf.errwarmessage err ON (el.value ->> 'key'::text) = :code and (el.value ->> 'value'::text) = :codeType ")
            .append("	where (:clientId::integer is null or cl.client_id = :clientId::integer) and cl.record_status_id = :suspectedRecordStatusId ")
            .append("	AND (:clientJobScheduleId::bigint is null or acc.client_job_schedule_id = :clientJobScheduleId::bigint) ")
            .append("	AND coalesce(date(cl.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(cl.dtm_utc_create), current_date)  ")
            .append("	AND coalesce(date(cl.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(cl.dtm_utc_create), current_date) ")
            .append("	group by cl.chargeoff_account_id, cl.client_id, cl.client_account_number ")
            .toString();

    public static final String GET_ACCOUNT_TAG_DETAIL_FOR_SUSPECTED = new StringBuffer()
            .append("	select cl.account_tag_id accountTagId, cl.client_id clientId, cl.client_account_number clientAccountNumber ")
            .append("	from data.account_tag cl  ")
            .append("	inner join data.account acc ON acc.client_id = cl.client_id and acc.client_account_number = cl.client_account_number ")
            .append("	CROSS JOIN LATERAL json_array_elements(cl.err_code_json::json) el(value) ")
            .append("	JOIN conf.errwarmessage err ON (el.value ->> 'key'::text) = :code and (el.value ->> 'value'::text) = :codeType ")
            .append("	where (:clientId::integer is null or cl.client_id = :clientId::integer) and cl.record_status_id = :suspectedRecordStatusId ")
            .append("	AND (:clientJobScheduleId::bigint is null or acc.client_job_schedule_id = :clientJobScheduleId::bigint) ")
            .append("	AND coalesce(date(cl.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(cl.dtm_utc_create), current_date)  ")
            .append("	AND coalesce(date(cl.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(cl.dtm_utc_create), current_date) ")
            .append("	group by cl.account_tag_id, cl.client_id, cl.client_account_number ")
            .toString();

    public static final String GET_CHAIN_OF_TITLE_DETAIL_FOR_SUSPECTED = new StringBuffer()
            .append("	select cl.chainoftitle_id chainoftitleId, cl.client_id clientId, cl.client_account_number clientAccountNumber ")
            .append("	from data.chainoftitle cl  ")
            .append("	inner join data.account acc ON acc.client_id = cl.client_id and acc.client_account_number = cl.client_account_number ")
            .append("	CROSS JOIN LATERAL json_array_elements(cl.err_code_json::json) el(value) ")
            .append("	JOIN conf.errwarmessage err ON (el.value ->> 'key'::text) = :code and (el.value ->> 'value'::text) = :codeType ")
            .append("	where (:clientId::integer is null or cl.client_id = :clientId::integer) and cl.record_status_id = :suspectedRecordStatusId ")
            .append("	AND (:clientJobScheduleId::bigint is null or acc.client_job_schedule_id = :clientJobScheduleId::bigint) ")
            .append("	AND coalesce(date(cl.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(cl.dtm_utc_create), current_date)  ")
            .append("	AND coalesce(date(cl.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(cl.dtm_utc_create), current_date) ")
            .append("	group by cl.chainoftitle_id, cl.client_id, cl.client_account_number ")
            .toString();

    public static final String GET_LEGAL_FOR_SUSPECTED = new StringBuffer()
            .append("	select lp.legal_placement_id legalPlacementId, lp.client_id clientId, lp.client_account_number clientAccountNumber ")
            .append("	from data.legal_placement lp ")
            .append("   inner join data.account acc ON acc.client_id = lp.client_id and acc.client_account_number = lp.client_account_number ")
            .append("   CROSS JOIN LATERAL json_array_elements(lp.err_code_json::json) el(value) ")
            .append("   JOIN conf.errwarmessage err ON (el.value ->> 'key'::text) = :code and (el.value ->> 'value'::text) = :codeType ")
            .append("   where (:clientId::integer is null or lp.client_id = :clientId::integer) and lp.record_status_id = :suspectedRecordStatusId ")
            .append("   AND (:clientJobScheduleId::bigint is null or acc.client_job_schedule_id = :clientJobScheduleId::bigint) ")
            .append("   AND coalesce(date(lp.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(lp.dtm_utc_create), current_date) ")
            .append("   AND coalesce(date(lp.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(lp.dtm_utc_create), current_date) ")
            .append("   group by lp.legal_placement_id, lp.client_id, lp.client_account_number ")
            .toString();

    public static final String GET_LIEN_FOR_SUSPECTED = new StringBuffer()
            .append("	select cl.legal_lien_id legalLienId, cl.client_id clientId, cl.client_account_number clientAccountNumber ")
            .append("	from data.legal_lien cl  ")
            .append("	inner join data.account acc ON acc.client_id = cl.client_id and acc.client_account_number = cl.client_account_number ")
            .append("	CROSS JOIN LATERAL json_array_elements(cl.err_code_json::json) el(value) ")
            .append("	JOIN conf.errwarmessage err ON (el.value ->> 'key'::text) = :code and (el.value ->> 'value'::text) = :codeType ")
            .append("	where (:clientId::integer is null or cl.client_id = :clientId::integer) and cl.record_status_id = :suspectedRecordStatusId ")
            .append("	AND (:clientJobScheduleId::bigint is null or acc.client_job_schedule_id = :clientJobScheduleId::bigint) ")
            .append("	AND coalesce(date(cl.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(cl.dtm_utc_create), current_date)  ")
            .append("	AND coalesce(date(cl.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(cl.dtm_utc_create), current_date) ")
            .append("	group by cl.legal_lien_id, cl.client_id, cl.client_account_number ")
            .toString();

    public static final String GET_GARNISHMENT_FOR_SUSPECTED = new StringBuffer()
            .append("	select cl.legal_garnishment_id  legalgarnishmentid, cl.client_id clientId, cl.client_account_number clientAccountNumber  ")
            .append("	from data.legal_garnishment cl  ")
            .append("	inner join data.account acc ON acc.client_id = cl.client_id and acc.client_account_number = cl.client_account_number ")
            .append("	CROSS JOIN LATERAL json_array_elements(cl.err_code_json::json) el(value) ")
            .append("	JOIN conf.errwarmessage err ON (el.value ->> 'key'::text) = :code and (el.value ->> 'value'::text) = :codeType ")
            .append("	where (:clientId::integer is null or cl.client_id = :clientId::integer) and cl.record_status_id = :suspectedRecordStatusId ")
            .append("	AND (:clientJobScheduleId::bigint is null or acc.client_job_schedule_id = :clientJobScheduleId::bigint) ")
            .append("	AND coalesce(date(cl.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(cl.dtm_utc_create), current_date)  ")
            .append("	AND coalesce(date(cl.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(cl.dtm_utc_create), current_date) ")
            .append("	group by cl.legal_garnishment_id, cl.client_id, cl.client_account_number ")
            .toString();

    public static final String GET_BANKRUPTCY_FOR_SUSPECTED = new StringBuffer()
            .append(" SELECT b.bankruptcy_id bankruptcyId, b.client_id clientId, b.client_account_number clientAccountNumber ")
            .append(" FROM data.bankruptcy b ")
            .append(" INNER JOIN data.account acc ON acc.client_id = b.client_id and acc.client_account_number = b.client_account_number ")
            .append(" CROSS JOIN LATERAL json_array_elements(b.err_code_json::json) el(value) ")
            .append(" JOIN conf.errwarmessage err ON (el.value ->> 'key'::text) = :code and (el.value ->> 'value'::text) = :codeType ")
            .append(" WHERE (:clientId::integer is null or b.client_id = :clientId::integer) and b.record_status_id = :suspectedRecordStatusId ")
            .append(" AND (:clientJobScheduleId::bigint is null or acc.client_job_schedule_id = :clientJobScheduleId::bigint) ")
            .append(" AND coalesce(date(b.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(b.dtm_utc_create), current_date) ")
            .append(" AND coalesce(date(b.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(b.dtm_utc_create), current_date) ")
            .append(" GROUP BY b.bankruptcy_id, b.client_id, b.client_account_number ")
            .toString();

    public static final String GET_COMPLAINT_FOR_SUSPECTED = new StringBuffer()
            .append(" SELECT c.complaint_id complaintId, c.client_id clientId, c.client_account_number clientAccountNumber ")
            .append(" FROM data.complaint c ")
            .append(" INNER JOIN data.account acc ON acc.client_id = c.client_id and acc.client_account_number = c.client_account_number ")
            .append(" CROSS JOIN LATERAL json_array_elements(c.err_code_json::json) el(value) ")
            .append(" JOIN conf.errwarmessage err ON (el.value ->> 'key'::text) = :code and (el.value ->> 'value'::text) = :codeType ")
            .append(" WHERE (:clientId::integer is null or c.client_id = :clientId::integer) and c.record_status_id = :suspectedRecordStatusId ")
            .append(" AND (:clientJobScheduleId::bigint is null or acc.client_job_schedule_id = :clientJobScheduleId::bigint) ")
            .append(" AND coalesce(date(c.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(c.dtm_utc_create), current_date) ")
            .append(" AND coalesce(date(c.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(c.dtm_utc_create), current_date) ")
            .append(" GROUP BY c.complaint_id, c.client_id, c.client_account_number ")
            .toString();

    public static final String GET_DISPUTE_FOR_SUSPECTED = new StringBuffer()
            .append(" SELECT d.dispute_id disputeId, d.client_id clientId, d.client_account_number clientAccountNumber ")
            .append(" FROM data.dispute d ")
            .append(" INNER JOIN data.account acc ON acc.client_id = d.client_id and acc.client_account_number = d.client_account_number ")
            .append(" CROSS JOIN LATERAL json_array_elements(d.err_code_json::json) el(value) ")
            .append(" JOIN conf.errwarmessage err ON (el.value ->> 'key'::text) = :code and (el.value ->> 'value'::text) = :codeType ")
            .append(" WHERE (:clientId::integer is null or d.client_id = :clientId::integer) and d.record_status_id = :suspectedRecordStatusId ")
            .append(" AND (:clientJobScheduleId::bigint is null or acc.client_job_schedule_id = :clientJobScheduleId::bigint) ")
            .append(" AND coalesce(date(d.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(d.dtm_utc_create), current_date) ")
            .append(" AND coalesce(date(d.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(d.dtm_utc_create), current_date) ")
            .append(" GROUP BY d.dispute_id, d.client_id, d.client_account_number ")
            .toString();

    public static final String GET_COMMUNICATION_DETAIL_FOR_SUSPECTED = new StringBuffer()
            .append("	select cl.communication_detail_id communicationDetailId, cl.client_id clientId, cl.client_account_number clientAccountNumber ")
            .append("	from data.communication_detail cl  ")
            .append("	inner join data.account acc ON acc.client_id = cl.client_id and acc.client_account_number = cl.client_account_number ")
            .append("	CROSS JOIN LATERAL json_array_elements(cl.err_code_json::json) el(value) ")
            .append("	JOIN conf.errwarmessage err ON (el.value ->> 'key'::text) = :code and (el.value ->> 'value'::text) = :codeType ")
            .append("	where (:clientId::integer is null or cl.client_id = :clientId::integer) and cl.record_status_id = :suspectedRecordStatusId ")
            .append("	AND (:clientJobScheduleId::bigint is null or acc.client_job_schedule_id = :clientJobScheduleId::bigint) ")
            .append("	AND coalesce(date(cl.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(cl.dtm_utc_create), current_date)  ")
            .append("	AND coalesce(date(cl.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(cl.dtm_utc_create), current_date) ")
            .append("	group by cl.communication_detail_id, cl.client_id, cl.client_account_number ")
            .toString();

    public static final String GET_ACCOUNT_DATA_SCRUBBING_DOWNLOAD = new StringBuffer()
            .append("	select ")
            .append("		acc.account_id accountid, cl.full_name clientname, acc.client_account_number clientaccountnumber,  ")
            .append("		acc.original_account_number originalaccountnumber, case when acc.errwar_type='e' then acc.errwar_short_name else CONCAT('W', SUBSTRING(acc.errwar_short_name,2)) end errorcode, acc.errwar_description errordescription ")
            .append("	from  ")
            .append("		data.vwerrwarmessage_account acc  ")
            .append("	join  ")
            .append("		data.account account on acc.client_id = account.client_id and acc.client_account_number = account.client_account_number   ")
            .append("	join  ")
            .append("		conf.client cl on acc.client_id = cl.client_id  ")
            .append("	where  (:clientId::integer is null or acc.client_id = :clientId::integer) and (:clientJobScheduleId::bigint is null or acc.client_job_schedule_id = :clientJobScheduleId::bigint) and  coalesce(date(acc.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(acc.dtm_utc_create), current_date)  ")
            .append("		and coalesce(date(acc.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(acc.dtm_utc_create), current_date)  ")
            .append("		and account.record_status_id = "+ ConfRecordStatus.confRecordStatus.get(ConfRecordStatus.SUSPECTED).getRecordStatusId()+"  ")
            .append("	order by  ")
            .append("		acc.account_id asc  ")
            .toString();
    public static final String GET_CONSUMER_DATA_SCRUBBING_DOWNLOAD = new StringBuffer()
            .append("	select ")
            .append("		con.consumer_id consumerid, cl.full_name clientname, con.client_account_number clientaccountnumber,  ")
            .append("		case when con.errwar_type='e' then con.errwar_short_name else CONCAT('W', SUBSTRING(con.errwar_short_name,2)) end errorcode, con.errwar_description errordescription ")
            .append("	from  ")
            .append("		data.vwerrwarmessage_consumer con  ")
//			.append("	join  ")
//			.append("		data.account acc on acc.client_id = con.client_id and acc.client_account_number = con.client_account_number  ")
            .append("	join  ")
            .append("		data.consumer consumer on con.consumer_id = consumer.consumer_id  ")
            .append("	join  ")
            .append("		conf.client cl on con.client_id = cl.client_id  ")
            .append("	where  (:clientId::integer is null or con.client_id = :clientId::integer) and (:clientJobScheduleId::bigint is null or con.client_job_schedule_id = :clientJobScheduleId::bigint) and  coalesce(date(con.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(con.dtm_utc_create), current_date)  ")
            .append("		and coalesce(date(con.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(con.dtm_utc_create), current_date)  ")
            .append("		and consumer.record_status_id = "+ConfRecordStatus.confRecordStatus.get(ConfRecordStatus.SUSPECTED).getRecordStatusId()+"  ")
            .append("	order by  ")
            .append("		con.consumer_id asc  ")
            .toString();

    public static final String GET_ADDRESS_DATA_SCRUBBING_DOWNLOAD = new StringBuffer()
            .append("	select ")
            .append("		add.address_id addressid, cl.full_name clientname, add.client_account_number clientaccountnumber,  ")
            .append("		case when add.errwar_type='e' then add.errwar_short_name else CONCAT('W', SUBSTRING(add.errwar_short_name,2)) end errorcode, add.errwar_description errordescription ")
            .append("	from  ")
            .append("		data.vwerrwarmessage_address add  ")
//			.append("	join  ")
//			.append("		data.account acc on acc.client_id = add.client_id and acc.client_account_number = add.client_account_number  ")
            .append("	join  ")
            .append("		data.address address on add.address_id = address.address_id  ")
            .append("	join  ")
            .append("		conf.client cl on add.client_id = cl.client_id  ")
            .append("	where  (:clientId::integer is null or add.client_id = :clientId::integer) and (:clientJobScheduleId::bigint is null or add.client_job_schedule_id = :clientJobScheduleId::bigint) and  coalesce(date(add.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(add.dtm_utc_create), current_date)  ")
            .append("		and coalesce(date(add.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(add.dtm_utc_create), current_date)  ")
            .append("		and address.record_status_id = "+ConfRecordStatus.confRecordStatus.get(ConfRecordStatus.SUSPECTED).getRecordStatusId()+"  ")
            .append("	order by  ")
            .append("		add.address_id asc  ")
            .toString();

    public static final String GET_PHONE_DATA_SCRUBBING_DOWNLOAD = new StringBuffer()
            .append("	select ")
            .append("		ph.phone_id phoneid, cl.full_name clientname, ph.client_account_number clientaccountnumber,  ")
            .append("		case when ph.errwar_type='e' then ph.errwar_short_name else CONCAT('W', SUBSTRING(ph.errwar_short_name,2)) end errorcode, ph.errwar_description errordescription ")
            .append("	from  ")
            .append("		data.vwerrwarmessage_phone ph  ")
//			.append("	join  ")
//			.append("		data.account acc on acc.client_id = ph.client_id and acc.client_account_number = ph.client_account_number  ")
            .append("	join  ")
            .append("		data.phone phone on ph.phone_id = phone.phone_id  ")
            .append("	join  ")
            .append("		conf.client cl on ph.client_id = cl.client_id  ")
            .append("	where  (:clientId::integer is null or ph.client_id = :clientId::integer) and (:clientJobScheduleId::bigint is null or ph.client_job_schedule_id = :clientJobScheduleId::bigint) and  coalesce(date(ph.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(ph.dtm_utc_create), current_date)  ")
            .append("		and coalesce(date(ph.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(ph.dtm_utc_create), current_date)  ")
            .append("		and phone.record_status_id = "+ConfRecordStatus.confRecordStatus.get(ConfRecordStatus.SUSPECTED).getRecordStatusId()+"  ")
            .append("	order by  ")
            .append("		ph.phone_id asc  ")
            .toString();

    public static final String GET_EMAIL_DATA_SCRUBBING_DOWNLOAD = new StringBuffer()
            .append("	select ")
            .append("		em.email_id emailid, cl.full_name clientname, em.client_account_number clientaccountnumber,  ")
            .append("		case when em.errwar_type='e' then em.errwar_short_name else CONCAT('W', SUBSTRING(em.errwar_short_name,2)) end errorcode, em.errwar_description errordescription ")
            .append("	from  ")
            .append("		data.vwerrwarmessage_email em  ")
//			.append("	join  ")
//			.append("		data.account acc on acc.client_id = em.client_id and acc.client_account_number = em.client_account_number  ")
            .append("	join  ")
            .append("		data.email email on em.email_id = email.email_id  ")
            .append("	join  ")
            .append("		conf.client cl on em.client_id = cl.client_id  ")
            .append("	where (:clientId::integer is null or em.client_id = :clientId::integer) and (:clientJobScheduleId::bigint is null or em.client_job_schedule_id = :clientJobScheduleId::bigint) and coalesce(date(em.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(em.dtm_utc_create), current_date)  ")
            .append("		and coalesce(date(em.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(em.dtm_utc_create), current_date)  ")
            .append("		and email.record_status_id = "+ConfRecordStatus.confRecordStatus.get(ConfRecordStatus.SUSPECTED).getRecordStatusId()+"  ")
            .append("	order by  ")
            .append("		em.email_id asc  ")
            .toString();

    public static final String GET_PAYMENT_DATA_SCRUBBING_DOWNLOAD = new StringBuffer()
            .append("	select ")
            .append("		pay.payment_id paymentid, payment.account_id, pay.client_account_number, cl.full_name clientname,p.full_name partnernname,  ")
            .append("		payment.payment_plan_id, payment.payment_serial, payment.amt_payment, payment.payment_method, payment.dt_payment, payment. payment_status, payment.payment_type, ")
            .append("		payment.dt_payment_posting,payment.amt_balance, payment.payment_broken_reason,payment.approval_code, payment.partner_batch_number, payment.posting_number, ")
            .append("		payment.gateway_vendor, payment.count_balance_payment, payment.amt_principal, payment.amt_interest, payment.amt_latefee,payment.amt_otherfee,payment.amt_courtcost,  ")
            .append("		payment.reversal_parent_id, payment.payment_settlement_type, payment.is_commissionable,payment.payment_source, payment.err_code_json, ")
            .append("       case when pay.errwar_type='e' then pay.errwar_short_name else CONCAT('W', SUBSTRING(pay.errwar_short_name,2)) end errorcode ")
            .append("	from  ")
            .append("		data.vwerrwarmessage_payment pay  ")
            .append("	join  ")
            .append("		data.payment payment on pay.payment_id = payment.payment_id   ")
            .append("	join  ")
            .append("		conf.client cl on pay.client_id = cl.client_id  ")
            .append("	left join  ")
            .append("		conf.partner p on payment.partner_id = p.partner_id  ")
            .append("	where (:clientId::integer is null or pay.client_id = :clientId::integer) and (:clientJobScheduleId::bigint is null or pay.client_job_schedule_id = :clientJobScheduleId::bigint) and coalesce(date(pay.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(pay.dtm_utc_create), current_date)  ")
            .append("		and coalesce(date(pay.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(pay.dtm_utc_create), current_date)  ")
            .append("		and payment.record_status_id = "+ConfRecordStatus.confRecordStatus.get(ConfRecordStatus.SUSPECTED).getRecordStatusId()+"  ")
            .append("	order by  ")
            .append("		pay.payment_id asc  ")
            .toString();

    public static final String GET_PAYMENT_PLAN_DATA_SCRUBBING_DOWNLOAD = new StringBuffer()
            .append("	select ")
            .append("		pp.payment_plan_id paymentplanid, pp.account_id, pp.client_account_number,cl.full_name clientname,p.full_name partnername, ppbr.lookup_value paymentplanbrokenreason, ")
            .append("		pp.partner_plan_number, pp.pct_discount, pp.count_payment, pp.dt_settlement, pp.amt_settlement, pp.amt_downpayment,pp.dt_downpayment, ")
            .append("		ppr.lookup_value paymentplanreason, ppi.lookup_value paymentplaninterval, ppt.lookup_value paymentplantype, pps.lookup_value paymentplanstatus, pm.lookup_value paymentmethod, ")
            .append("       case when (el.value ->> 'key'::text)='e' then err.short_name else CONCAT('W', SUBSTRING(err.short_name,2)) end errorcode, err.description ")
            .append("	from  ")
            .append("		data.payment_plan pp   ")
            .append("	join  ")
            .append("		data.account acc on acc.client_id = pp.client_id and acc.client_account_number = pp.client_account_number  ")
            .append("	CROSS JOIN LATERAL json_array_elements(pp.err_code_json::json) el(value)  ")
            .append("	join  ")
            .append("		conf.errwarmessage err ON (el.value ->> 'value'::text) = err.short_name::text ")
            .append("	join  ")
            .append("		conf.client cl on pp.client_id = cl.client_id  ")
            .append("	left join  ")
            .append("		conf.partner p on pp.partner_id = p.partner_id  ")
            .append("	left join  ")
            .append("		conf.vwlookup ppbr on ppbr.keycode = pp.payment_plan_broken_reason and ppbr.lookup_group_value = 'payment_plan_broken_reason'  ")
            .append("	left join  ")
            .append("		conf.vwlookup ppr on ppr.keycode = pp.payment_plan_reason and ppr.lookup_group_value = 'payment_plan_reason'  ")
            .append("	left join  ")
            .append("		conf.vwlookup ppi on ppi.keycode = pp.payment_plan_interval and ppi.lookup_group_value = 'payment_plan_interval'  ")
            .append("	left join  ")
            .append("		conf.vwlookup ppt on ppt.keycode = pp.payment_plan_type and ppt.lookup_group_value = 'payment_plan_type'  ")
            .append("	left join  ")
            .append("		conf.vwlookup pps on pps.keycode = pp.payment_plan_status and pps.lookup_group_value = 'payment_plan_status'  ")
            .append("	left join  ")
            .append("		conf.vwlookup pm on pm.keycode = pp.payment_method and pm.lookup_group_value = 'payment_method'  ")
            .append("	where (:clientId::integer is null or pp.client_id = :clientId::integer) and (:clientJobScheduleId::bigint is null or acc.client_job_schedule_id = :clientJobScheduleId::bigint) and coalesce(date(pp.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(pp.dtm_utc_create), current_date)  ")
            .append("		and coalesce(date(pp.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(pp.dtm_utc_create), current_date)  ")
            .append("		and pp.record_status_id = "+ConfRecordStatus.confRecordStatus.get(ConfRecordStatus.SUSPECTED).getRecordStatusId()+"  ")
            .append("	order by  ")
            .append("		pp.payment_plan_id asc  ")
            .toString();

    public static final String GET_CHANGELOG_DATA_SCRUBBING_DOWNLOAD = new StringBuffer()
            .append("	select ")
            .append("		cl.changelog_id changelogid, cl.account_id, cl.client_account_number,c.full_name clientname,  ")
            .append("		cl.attribute_name, cl.external_source_id, cl. external_system_id, cl.previous_value, cl.new_value, cl.failed_reason, cl.consumer_id, cl.client_consumer_number, ")
            .append("		cl.entity_short_name, cl.external_source_type, ")
            .append("       case when (el.value ->> 'key'::text)='e' then err.short_name else CONCAT('W', SUBSTRING(err.short_name,2)) end errorcode, err.description ")
            .append("	from  ")
            .append("		data.changelog cl    ")
            .append("	join  ")
            .append("		data.account acc on acc.client_id = cl.client_id and acc.client_account_number = cl.client_account_number  ")
            .append("	CROSS JOIN LATERAL json_array_elements(cl.err_code_json::json) el(value)  ")
            .append("	join  ")
            .append("		conf.errwarmessage err ON (el.value ->> 'value'::text) = err.short_name::text ")
            .append("	join  ")
            .append("		conf.client c on cl.client_id = c.client_id  ")
            .append("	where (:clientId::integer is null or cl.client_id = :clientId::integer) and (:clientJobScheduleId::bigint is null or acc.client_job_schedule_id = :clientJobScheduleId::bigint) and coalesce(date(cl.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(cl.dtm_utc_create), current_date)  ")
            .append("		and coalesce(date(cl.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(cl.dtm_utc_create), current_date)  ")
            .append("		and cl.record_status_id = "+ConfRecordStatus.confRecordStatus.get(ConfRecordStatus.SUSPECTED).getRecordStatusId()+"  ")
            .append("	order by  ")
            .append("		cl.changelog_id asc  ")
            .toString();
    public static final String GET_EMPLOYER_DATA_SCRUBBING_DOWNLOAD = new StringBuffer()
            .append("	select ")
            .append("		e.employer_id employerid, e.account_id, e.client_account_number,cl.full_name clientname,  ")
            .append("		e.client_employer_number,e.contact_id, e.full_name,e.address1,e.address2,e.state_code,e.city,e.zip, e.phone,  ")
            .append("		e.consumer_id, e.client_consumer_number, e.fax, e.country,e.consumer_identification_number, e.consumer_title, ")
            .append("		e.consumer_first_name, e.consumer_middle_name, e.consumer_last_name, e.consumer_position, e.consumer_manager_full_name, ")
            .append("		e.consumer_employee_id, e.consumer_employment_disclaimer, e.consumer_payroll_disclaimer,e.amt_consumer_wages, ")
            .append("		e.consumer_division_code, e.dt_consumer_joining, e.count_consumer_servicemonth, e.dt_consumer_most_recent_update, e.dt_consumer_termination, ")
            .append("		e.legal_code, e.is_active, pm.lookup_value employerappendstatus, ppt.lookup_value consumerwagepayfrequency, ")
            .append("       case when (el.value ->> 'key'::text)='e' then err.short_name else CONCAT('W', SUBSTRING(err.short_name,2)) end errorcode, err.description ")
            .append("	from  ")
            .append("		data.employer e    ")
            .append("	join  ")
            .append("		data.account acc on acc.client_id = e.client_id and acc.client_account_number = e.client_account_number  ")
            .append("	CROSS JOIN LATERAL json_array_elements(e.err_code_json::json) el(value)  ")
            .append("	join  ")
            .append("		conf.errwarmessage err ON (el.value ->> 'value'::text) = err.short_name::text ")
            .append("	join  ")
            .append("		conf.client cl on e.client_id = cl.client_id  ")
            .append("	left join  ")
            .append("		conf.vwlookup pm on pm.keycode = e.employer_append_status and pm.lookup_group_value = 'employer_append_status' ")
            .append("	left join  ")
            .append("		conf.vwlookup ppt on ppt.keycode = e.consumer_wagepay_frequency and ppt.lookup_group_value = 'consumer_wagepay_frequency'  ")
            .append("	where (:clientId::integer is null or e.client_id = :clientId::integer) and (:clientJobScheduleId::bigint is null or acc.client_job_schedule_id = :clientJobScheduleId::bigint) and coalesce(date(e.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(e.dtm_utc_create), current_date)  ")
            .append("		and coalesce(date(e.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(e.dtm_utc_create), current_date)  ")
            .append("		and e.record_status_id = "+ConfRecordStatus.confRecordStatus.get(ConfRecordStatus.SUSPECTED).getRecordStatusId()+"  ")
            .append("	order by  ")
            .append("		e.employer_id asc  ")
            .toString();

    public static final String GET_COMPLIANCE_DATA_SCRUBBING_DOWNLOAD = new StringBuffer()
            .append("	select ")
            .append("		c.compliance_id complianceid, c.account_id, c.client_account_number,cl.full_name clientname,p.full_name partnername, ")
            .append("		pt.lookup_value compliancecategory,c.client_consumer_number, c.consumer_id, c.contact_id, pm.lookup_value compliancetype, c.dt_report, c.description_reported,  ")
            .append("		pp.lookup_value compliancechannel, c.contact_detail, pq.lookup_value compliancestatus, ppt.lookup_value bankruptcytype,pcm.lookup_value compliancemode, ")
            .append("		c.description_resolution, c.dt_resolution, pcr.lookup_value compliancereason, c.is_validation_required, c.remark_comment, c.dt_filing, c.is_regulatory, c.regulatorybody_id, ")
            .append("		c.dt_firstsla, c.dt_firstsla_calculation, c.dt_lastsla, c.dt_lastsla_calculation, c.case_file_number,c.amt_principle, c.amt_interest, c.amt_fee, c.amt_total, c.court_city, ")
            .append("		pcs.lookup_value compliancesubtype,c.is_additionaltime_required, c.regulatorybody_short_name, c.reported_by, c.external_system_id, c.is_voluntary, pcd.lookup_value compliancedisposition, ")
            .append("		c.consumer_identification_number, c.dt_event,pca.lookup_value complianceaction, c.dt_due_claim_proof, c.dt_filed_claim_proof, c.defendant, c.is_attorney_assigned, c.dt_attorney_assigned, ")
            .append("		pat.lookup_value attorney_type, c.attorney_fax , c.amt_event_balance, c.amt_compliance_balance,	  ")
            .append("       case when (el.value ->> 'key'::text)='e' then err.short_name else CONCAT('W', SUBSTRING(err.short_name,2)) end errorcode, err.description ")
            .append("	from  ")
            .append("		data.compliance c ")
            .append("	join  ")
            .append("		data.account acc on acc.client_id = c.client_id and acc.client_account_number = c.client_account_number  ")
            .append("	CROSS JOIN LATERAL json_array_elements(c.err_code_json::json) el(value)  ")
            .append("	join  ")
            .append("		conf.errwarmessage err ON (el.value ->> 'value'::text) = err.short_name::text ")
            .append("	join  ")
            .append("		conf.client cl on c.client_id = cl.client_id  ")
            .append("	left join  ")
            .append("		conf.partner p on c.partner_id = p.partner_id  ")
            .append("	left join  ")
            .append("		conf.vwlookup pt on pt.keycode = c.compliance_category and pt.lookup_group_value = 'compliance_category' ")
            .append("	left join  ")
            .append("		conf.vwlookup pm on pm.keycode = c.compliance_type and pm.lookup_group_value = 'compliance_type'  ")
            .append("	left join  ")
            .append("			conf.vwlookup pp on pp.keycode = c.compliance_channel and pp.lookup_group_value = 'compliance_channel' ")
            .append("	left join  ")
            .append("		conf.vwlookup pq on pq.keycode = c.compliance_status and pq.lookup_group_value = 'compliance_status'  ")
            .append("	left join  ")
            .append("		conf.vwlookup ppt on ppt.keycode = c.bankruptcy_type and ppt.lookup_group_value = 'bankruptcy_type'  ")
            .append("	left join  ")
            .append("		conf.vwlookup pcm on pcm.keycode = c.compliance_mode and pcm.lookup_group_value = 'compliance_mode' ")
            .append("	left join  ")
            .append("		conf.vwlookup pcr on pcr.keycode = c.compliance_reason and pcr.lookup_group_value = 'compliance_reason'  ")
            .append("	left join  ")
            .append("		conf.vwlookup pcs on pcs.keycode = c.compliance_subtype and pcs.lookup_group_value = 'compliance_subtype'  ")
            .append("	left join  ")
            .append("		conf.vwlookup pcd on pcd.keycode = c.compliance_disposition and pcd.lookup_group_value = 'compliance_disposition'  ")
            .append("	left join  ")
            .append("		conf.vwlookup pca on pca.keycode = c.compliance_action and pca.lookup_group_value = 'compliance_action'  ")
            .append("	left join  ")
            .append("		conf.vwlookup pat on pat.keycode = c.attorney_type and pat.lookup_group_value = 'attorney_type' ")
            .append("	where (:clientId::integer is null or c.client_id = :clientId::integer) and (:clientJobScheduleId::bigint is null or acc.client_job_schedule_id = :clientJobScheduleId::bigint) and coalesce(date(c.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(c.dtm_utc_create), current_date)  ")
            .append("		and coalesce(date(c.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(c.dtm_utc_create), current_date)  ")
            .append("		and c.record_status_id = "+ConfRecordStatus.confRecordStatus.get(ConfRecordStatus.SUSPECTED).getRecordStatusId()+"  ")
            .append("	order by  ")
            .append("		c.compliance_id asc  ")
            .toString();

    public static final String GET_CHARGEOFF_ACCOUNT_DATA_SCRUBBING_DOWNLOAD = new StringBuffer()
            .append("	select ")
            .append("		ca.chargeoff_account_id  chargeoffaccountid, ca.account_id, ca.client_account_number,cl.full_name clientname, ")
            .append("		ca.amt_pre_charge_off_principal, ca.amt_pre_charge_off_interest,ca.amt_pre_charge_off_fee, ca.amt_pre_charge_off_balance, ca.dt_charge_off, ca.job_schedule_id,  ")
            .append("       case when (el.value ->> 'key'::text)='e' then err.short_name else CONCAT('W', SUBSTRING(err.short_name,2)) end errorcode, err.description ")
            .append("	from  ")
            .append("		data.chargeoff_account ca ")
            .append("	join  ")
            .append("		data.account acc on acc.client_id = ca.client_id and acc.client_account_number = ca.client_account_number  ")
            .append("	CROSS JOIN LATERAL json_array_elements(ca.err_code_json::json) el(value)  ")
            .append("	join  ")
            .append("		conf.errwarmessage err ON (el.value ->> 'value'::text) = err.short_name::text ")
            .append("	join  ")
            .append("		conf.client cl on ca.client_id = cl.client_id  ")
            .append("	where (:clientId::integer is null or ca.client_id = :clientId::integer) and (:clientJobScheduleId::bigint is null or acc.client_job_schedule_id = :clientJobScheduleId::bigint) and coalesce(date(ca.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(ca.dtm_utc_create), current_date)  ")
            .append("		and coalesce(date(ca.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(ca.dtm_utc_create), current_date)  ")
            .append("		and ca.record_status_id = "+ConfRecordStatus.confRecordStatus.get(ConfRecordStatus.SUSPECTED).getRecordStatusId()+"  ")
            .append("	order by  ")
            .append("		ca.chargeoff_account_id asc  ")
            .toString();

    public static final String GET_ACCOUNT_TAG_DATA_SCRUBBING_DOWNLOAD = new StringBuffer()
            .append("	select ")
            .append("		a.account_tag_id  accounttagid, a.account_id, a.client_account_number,cl.full_name clientname, ")
            .append("		a.entity_short_name, a.ref_entity_id, a.ref_entity_number, a.tag_name, a.tag_value,   ")
            .append("       case when (el.value ->> 'key'::text)='e' then err.short_name else CONCAT('W', SUBSTRING(err.short_name,2)) end errorcode, err.description ")
            .append("	from  ")
            .append("		data.account_tag a  ")
            .append("	join  ")
            .append("		data.account acc on acc.client_id = a.client_id and acc.client_account_number = a.client_account_number  ")
            .append("	CROSS JOIN LATERAL json_array_elements(a.err_code_json::json) el(value)  ")
            .append("	join  ")
            .append("		conf.errwarmessage err ON (el.value ->> 'value'::text) = err.short_name::text ")
            .append("	join  ")
            .append("		conf.client cl on a.client_id = cl.client_id  ")
            .append("	where (:clientId::integer is null or a.client_id = :clientId::integer) and (:clientJobScheduleId::bigint is null or acc.client_job_schedule_id = :clientJobScheduleId::bigint) and coalesce(date(a.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(a.dtm_utc_create), current_date)  ")
            .append("		and coalesce(date(a.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(a.dtm_utc_create), current_date)  ")
            .append("		and a.record_status_id = "+ConfRecordStatus.confRecordStatus.get(ConfRecordStatus.SUSPECTED).getRecordStatusId()+"  ")
            .append("	order by  ")
            .append("		a.account_tag_id asc  ")
            .toString();

    public static final String GET_CHAIN_OF_TITLE_DATA_SCRUBBING_DOWNLOAD = new StringBuffer()
            .append("	select ")
            .append("		c.chainoftitle_id  chainoftitleid, c.account_id, c.client_account_number,cl.full_name clientname, ")
            .append("		ot.lookup_value cotownertype, c.cot_owner_id, c.cot_external_system_id, c.owner_external_system_id, c.external_subpool_id, ")
            .append("		c.subpool_owner_id, c.dt_from, c.dt_till, c.cot_status_id, c.remark_comment, ")
            .append("       case when (el.value ->> 'key'::text)='e' then err.short_name else CONCAT('W', SUBSTRING(err.short_name,2)) end errorcode, err.description ")
            .append("	from  ")
            .append("		data.chainoftitle c  ")
            .append("	join  ")
            .append("		data.account acc on acc.client_id = c.client_id and acc.client_account_number = c.client_account_number  ")
            .append("	CROSS JOIN LATERAL json_array_elements(c.err_code_json::json) el(value)  ")
            .append("	join  ")
            .append("		conf.errwarmessage err ON (el.value ->> 'value'::text) = err.short_name::text ")
            .append("	join  ")
            .append("		conf.client cl on c.client_id = cl.client_id  ")
            .append("	left join  ")
            .append("		conf.vwlookup ot on ot.keycode = c.cot_owner_type and ot.lookup_group_value = 'cot_owner_type' ")
            .append("	where (:clientId::integer is null or c.client_id = :clientId::integer) and (:clientJobScheduleId::bigint is null or acc.client_job_schedule_id = :clientJobScheduleId::bigint) and coalesce(date(c.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(c.dtm_utc_create), current_date)  ")
            .append("		and coalesce(date(c.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(c.dtm_utc_create), current_date)  ")
            .append("		and c.record_status_id = "+ConfRecordStatus.confRecordStatus.get(ConfRecordStatus.SUSPECTED).getRecordStatusId()+"  ")
            .append("	order by  ")
            .append("		c.chainoftitle_id asc  ")
            .toString();

    public static final String GET_COMMUNICATION_DETAIL_DATA_SCRUBBING_DOWNLOAD = new StringBuffer()
            .append("	select ")
            .append("		cd.communication_detail_id  communicationdetailid, cd.account_id, cd.client_account_number,cl.full_name clientname, ")
            .append("		cd.client_consumer_number, cc.lookup_value communicationchannel, cd.dt_communication, co.lookup_value communicationoutcome, ")
            .append("		cd.direction, cd.disposition, cd.tokens, cd.details, cd.is_rpc_received, cd.dt_rpc, cd.pct_discount, cd.tm_utc_communication, ")
            .append("		cd.timezone_name, cr.lookup_value communicationreason, cs.lookup_value communication_subreason, ct.lookup_value compliancetype, ")
            .append("		cd.dt_compliance, cd.remark_comment, csu.lookup_value compliancesubtype, cd.dt_outcome, cd.tm_utc_outcome, cd.regulatorybody_id, cd.regulatorybody_short_name, cd.communication_source, cd.communication_source_id, ")
            .append("       case when (el.value ->> 'key'::text)='e' then err.short_name else CONCAT('W', SUBSTRING(err.short_name,2)) end errorcode, err.description ")
            .append("	from  ")
            .append("		data.communication_detail cd  ")
            .append("	join  ")
            .append("		data.account acc on acc.client_id = cd.client_id and acc.client_account_number = cd.client_account_number  ")
            .append("	CROSS JOIN LATERAL json_array_elements(cd.err_code_json::json) el(value)  ")
            .append("	join  ")
            .append("		conf.errwarmessage err ON (el.value ->> 'value'::text) = err.short_name::text ")
            .append("	join  ")
            .append("		conf.client cl on cd.client_id = cl.client_id  ")
            .append("	left join  ")
            .append("		conf.vwlookup cc on cc.keycode = cd.communication_channel and cc.lookup_group_value = 'communication_channel' ")
            .append("	left join  ")
            .append("		conf.vwlookup co on co.keycode = cd.communication_outcome and co.lookup_group_value = 'communication_outcome' ")
            .append("	left join  ")
            .append("		conf.vwlookup cr on cr.keycode = cd.communication_reason and cr.lookup_group_value = 'communication_reason' ")
            .append("	left join  ")
            .append("		conf.vwlookup cs on cs.keycode = cd.communication_subreason and cs.lookup_group_value = 'communication_subreason' ")
            .append("	left join  ")
            .append("		conf.vwlookup ct on ct.keycode = cd.compliance_type and ct.lookup_group_value = 'compliance_type' ")
            .append("	left join  ")
            .append("		conf.vwlookup csu on csu.keycode = cd.compliance_subtype and csu.lookup_group_value = 'compliance_subtype' ")
            .append("	where (:clientId::integer is null or cd.client_id = :clientId::integer) and (:clientJobScheduleId::bigint is null or acc.client_job_schedule_id = :clientJobScheduleId::bigint) and coalesce(date(cd.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(cd.dtm_utc_create), current_date)  ")
            .append("		and coalesce(date(cd.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(cd.dtm_utc_create), current_date)  ")
            .append("		and cd.record_status_id = "+ConfRecordStatus.confRecordStatus.get(ConfRecordStatus.SUSPECTED).getRecordStatusId()+"  ")
            .append("	order by  ")
            .append("		cd.communication_detail_id asc  ")
            .toString();

    public static final String GET_LEGAL_SCRUBBING_DOWNLOAD = new StringBuffer()
            .append("  select lp.legal_placement_id  legalPlacementId, lp.account_id accountId, lp.client_account_number clientAccountNumber, cl.full_name clientName, lp.casenumber, ")
            .append("  lp.amt_judgement judgementAmount, lp.dt_judgement judgementDate, lp.judgment_status judgementStatus, lp.judgment_suit_outcome judgementSuitOutcome, ")
            .append("  case when (el.value ->> 'key'::text)='e' then err.short_name else CONCAT('W', SUBSTRING(err.short_name,2)) end errorcode, err.description ")
            .append("  from data.legal_placement lp ")
            .append("  join data.account acc on acc.client_id = lp.client_id and acc.client_account_number = lp.client_account_number ")
            .append("  CROSS JOIN LATERAL json_array_elements(lp.err_code_json::json) el(value) ")
            .append("  join conf.errwarmessage err ON (el.value ->> 'value'::text) = err.short_name::text ")
            .append("  join conf.client cl on lp.client_id = cl.client_id ")
            .append("  where (:clientId::integer is null or lp.client_id = :clientId::integer) and (:clientJobScheduleId::bigint is null or acc.client_job_schedule_id = :clientJobScheduleId::bigint) and coalesce(date(lp.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(lp.dtm_utc_create), current_date) ")
            .append("  and coalesce(date(lp.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(lp.dtm_utc_create), current_date) ")
            .append("  and lp.record_status_id = " + ConfRecordStatus.confRecordStatus.get(ConfRecordStatus.SUSPECTED).getRecordStatusId() + "  ")
            .append("  order by lp.legal_placement_id asc ")
            .toString();

    public static final String GET_LIEN_SCRUBBING_DOWNLOAD = new StringBuffer()
            .append("	select ")
            .append("		a.legal_lien_id  legalLienId, a.account_id accountId, a.client_account_number clientAccountNumber, cl.full_name clientName, ")
            .append("		a.casenumber, a.lien_type lienType, a.lien_asset lienAsset, a.amt_lien lienAmount, a.lien_status lienStatus, ")
            .append("       case when (el.value ->> 'key'::text)='e' then err.short_name else CONCAT('W', SUBSTRING(err.short_name,2)) end errorcode, err.description ")
            .append("	from  ")
            .append("		data.legal_lien a  ")
            .append("	join  ")
            .append("		data.account acc on acc.client_id = a.client_id and acc.client_account_number = a.client_account_number  ")
            .append("	CROSS JOIN LATERAL json_array_elements(a.err_code_json::json) el(value)  ")
            .append("	join  ")
            .append("		conf.errwarmessage err ON (el.value ->> 'value'::text) = err.short_name::text ")
            .append("	join  ")
            .append("		conf.client cl on a.client_id = cl.client_id  ")
            .append("	where (:clientId::integer is null or a.client_id = :clientId::integer) and (:clientJobScheduleId::bigint is null or acc.client_job_schedule_id = :clientJobScheduleId::bigint) and coalesce(date(a.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(a.dtm_utc_create), current_date)  ")
            .append("		and coalesce(date(a.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(a.dtm_utc_create), current_date)  ")
            .append("		and a.record_status_id = "+ConfRecordStatus.confRecordStatus.get(ConfRecordStatus.SUSPECTED).getRecordStatusId()+"  ")
            .append("	order by  ")
            .append("		a.legal_lien_id asc  ")
            .toString();

    public static final String GET_GARNISHMENT_SCRUBBING_DOWNLOAD = new StringBuffer()
            .append("	select ")
            .append("		l.legal_garnishment_id garnishmentId, l.account_id accountId, l.client_account_number clientAccountNumber, cl.full_name clientName, ")
            .append("		l.legal_placement_id legalPlacementId, l.casenumber, l.garnishment_type garnishmentType, l.amt_garnishment garnishmentAmount, l.dt_garnishment garnishmentDate, ")
            .append("		l. client_consumer_number clientConsumerNumber, l.consumer_id consumerId, l.garnishment_approver garnishmentApprover, la.lookup_value garnishmentStatus, l.payment_plan_id paymentPlanId, lb.lookup_value garnishmentFrequency, ")
            .append("       case when (el.value ->> 'key'::text)='e' then err.short_name else CONCAT('W', SUBSTRING(err.short_name,2)) end errorcode, err.description ")
            .append("	from  ")
            .append("		data.legal_garnishment l  ")
            .append("	join  ")
            .append("		data.account acc on acc.client_id = l.client_id and acc.client_account_number = l.client_account_number  ")
            .append("	CROSS JOIN LATERAL json_array_elements(l.err_code_json::json) el(value)  ")
            .append("	join  ")
            .append("		conf.errwarmessage err ON (el.value ->> 'value'::text) = err.short_name::text ")
            .append("	join  ")
            .append("		conf.client cl on l.client_id = cl.client_id  ")
            .append("	left join  ")
            .append("	    conf.vwlookup la on la.keycode = l.garnishment_status and la.lookup_group_value = 'garnishment_status'  ")
            .append("	left join  ")
            .append("	    conf.vwlookup lb on lb.keycode = l.garnishment_frequency and lb.lookup_group_value = 'garnishment_frequency'  ")
            .append("	where (:clientId::integer is null or l.client_id = :clientId::integer) and (:clientJobScheduleId::bigint is null or acc.client_job_schedule_id = :clientJobScheduleId::bigint) and coalesce(date(l.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(l.dtm_utc_create), current_date)  ")
            .append("		and coalesce(date(l.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(l.dtm_utc_create), current_date)  ")
            .append("		and l.record_status_id = "+ConfRecordStatus.confRecordStatus.get(ConfRecordStatus.SUSPECTED).getRecordStatusId()+"  ")
            .append("	order by  ")
            .append("		l.legal_garnishment_id asc  ")
            .toString();

    public static final String GET_BANKRUPTCY_SCRUBBING_DOWNLOAD = new StringBuffer()
            .append(" SELECT ")
            .append("   b.bankruptcy_id bankruptcyId, b.account_id accountId, b.client_account_number clientAccountNumber, cl.full_name clientName, b.bankruptcy_chapter bankruptcyChapter, ")
            .append("   b.dt_bankruptcy_filling dtBankruptcyFilling, b.dt_bankruptcy_report dtBankruptcyReport, b.bankruptcy_type bankruptcyType, b.channel, b.mode_of_receipt modeOfReceipt, ")
            .append("   b.bankruptcy_case_number bankruptcyCaseNumber, b.amt_principal_bankruptcy amtPrincipalBankruptcy, b.amt_interest_bankruptcy amtInterestBankruptcy, b.amt_fee_amount_bankruptcy amtFeeAmountBankruptcy, ")
            .append("   b.amt_total_bankruptcy amtTotalBankruptcy, b.bankruptcy_court_city bankruptcyCourtCity, b.bankruptcyCourtState, b.amt_balance_bankruptcy_filling amtBalanceBankruptcyFilling, ")
            .append("   b.amt_balance_bankruptcy_notified amtBalanceBankruptcyNotified, b.dt_claim_proof_due dtClaimProofDue, b.dt_claim_proof_filed dtClaimProofFiled, ")
            .append("   b.bankruptcy_petition_status bankruptcyPetitionStatus, b.bankruptcy_process_status bankruptcyProcessStatus, b.objection_status objectionStatus, b.automatic_stay_status automaticStayStatus, ")
            .append("   case when (el.value ->> 'key'::text)='e' then err.short_name else CONCAT('W', SUBSTRING(err.short_name,2)) end errorcode, err.description ")
            .append(" FROM data.bankruptcy b ")
            .append(" JOIN data.account acc on acc.client_id = b.client_id and acc.client_account_number = b.client_account_number")
            .append(" CROSS JOIN LATERAL json_array_elements(b.err_code_json::json) el(value) ")
            .append(" JOIN conf.errwarmessage err ON (el.value ->> 'value'::text) = err.short_name::text ")
            .append(" JOIN conf.client cl on b.client_id = cl.client_id ")
            .append(" WHERE (:clientId::integer is null or b.client_id = :clientId::integer) AND (:clientJobScheduleId::bigint is null OR acc.client_job_schedule_id = :clientJobScheduleId::bigint) AND coalesce(date(b.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(b.dtm_utc_create), current_date)")
            .append(" AND coalesce(date(b.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(b.dtm_utc_create), current_date) ")
            .append(" AND b.record_status_id = " + ConfRecordStatus.confRecordStatus.get(ConfRecordStatus.SUSPECTED).getRecordStatusId() + " ")
            .append(" ORDER BY b.bankruptcy_id asc")
            .toString();

    public static final String GET_COMPLAINT_SCRUBBING_DOWNLOAD = new StringBuffer()
            .append(" SELECT ")
            .append("   c.complaint_id complaintId, c.account_id accountId, c.client_account_number clientAccountNumber, cl.full_name clientName, ct.full_name complaintType, ")
            .append("   cr.full_name complaintReason, cc.lookup_value complaintChannel, cm.lookup_value channelMode, can.lookup_value complainant, c.dt_filling dtComplaintFilling, ")
            .append("   c.dt_report dtComplaintReport, c.description, c.is_debt_validation_required isDebtValidationRequired, rb.lookup_value regulatoryBody, ")
            .append("   c.dt_regulatory_draft_due dtRegulatoryDraftDue, c.dt_regulatory_due dtRegulatoryDue, cs.lookup_value complaintStatus, c.is_valid_complaint isValidComplaint, ")
            .append("   c.complaint_review complaintReview, c.is_remediation_required errorDescription, c.is_remediation_required isRemediationRequired, ")
            .append("   c.dt_remediation_due dtRemediationDue, c.remediation_type remediationType, c.remediation_description remediationDescription, c.remediation_summary remediationSummary, ")
            .append("   case when (el.value ->> 'key'::text)='e' then err.short_name else CONCAT('W', SUBSTRING(err.short_name,2)) end errorcode, err.description ")
            .append(" FROM data.complaint c ")
            .append(" JOIN data.account acc on acc.client_id = c.client_id and acc.client_account_number = c.client_account_number ")
            .append(" CROSS JOIN LATERAL json_array_elements(c.err_code_json::json) el(value) ")
            .append(" JOIN conf.errwarmessage err ON (el.value ->> 'value'::text) = err.short_name::text ")
            .append(" JOIN conf.client cl on c.client_id = cl.client_id ")
            .append(" LEFT JOIN conf.complaint_type ct on ct.short_name = c.complaint_type ")
            .append(" LEFT JOIN conf.complaint_reason cr on cr.short_name = c.complaint_reason ")
            .append(" LEFT JOIN conf.vwlookup cc on cc.keycode = c.complaint_channel and cc.lookup_group_value = 'compliance_channel' ")
            .append(" LEFT JOIN conf.vwlookup cm on cm.keycode = c.channel_mode and cm.lookup_group_value = 'compliance_mode' ")
            .append(" LEFT JOIN conf.vwlookup can on can.keycode = c.complainant and can.lookup_group_value = 'complainant' ")
            .append(" LEFT JOIN conf.vwlookup rb on rb.keycode = c.regulatory_body and rb.lookup_group_value = 'regulatory_body' ")
            .append(" LEFT JOIN conf.vwlookup cs on cs.keycode = c.complaint_status and cs.lookup_group_value = 'complaint_status' ")
            .append(" WHERE (:clientId::integer is null or c.client_id = :clientId::integer) AND (:clientJobScheduleId::bigint is null OR acc.client_job_schedule_id = :clientJobScheduleId::bigint) AND coalesce(date(c.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(c.dtm_utc_create), current_date) ")
            .append(" AND coalesce(date(c.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(c.dtm_utc_create), current_date) ")
            .append(" AND c.record_status_id = " + ConfRecordStatus.confRecordStatus.get(ConfRecordStatus.SUSPECTED).getRecordStatusId() + " ")
            .append(" ORDER BY c.complaint_id asc")
            .toString();

    public static final String GET_DISPUTE_SCRUBBING_DOWNLOAD = new StringBuffer()
            .append(" SELECT ")
            .append("   d.dispute_id disputeId, d.account_id accountId,d.client_account_number clientAccountNumber, cl.full_name clientName, ")
            .append("   d.consumer_id consumerId, d.client_consumer_number clientConsumerNumber, d.dt_filling dtDisputeFilling, d.dt_report dtDisputeReport, d.description,  ")
            .append("   d.is_debt_validation_required, d.dt_first_sla dtFirstSLA, d.dt_last_sla dtFinalSLA, dd.lookup_value disputeStatus, ")
            .append("   da.lookup_value channelMode, db.lookup_value disputeType, dc.lookup_value disputeChannel,  ")
            .append("   case when (el.value ->> 'key'::text)='e' then err.short_name else CONCAT('W', SUBSTRING(err.short_name,2)) end errorcode, err.description ")
            .append(" FROM data.dispute d    ")
            .append(" JOIN data.account acc on acc.client_id = d.client_id and acc.client_account_number = d.client_account_number")
            .append(" CROSS JOIN LATERAL json_array_elements(d.err_code_json::json) el(value)  ")
            .append(" JOIN conf.errwarmessage err ON (el.value ->> 'value'::text) = err.short_name::text  ")
            .append(" JOIN conf.client cl on d.client_id = cl.client_id ")
            .append("	left join  ")
            .append("	    conf.vwlookup da on da.keycode = d.channel_mode and da.lookup_group_value = 'channel_mode'  ")
            .append("	left join  ")
            .append("	    conf.vwlookup db on db.keycode = d.dispute_type and db.lookup_group_value = 'dispute_type'  ")
            .append("	left join  ")
            .append("	    conf.vwlookup dc on dc.keycode = d.dispute_channel and dc.lookup_group_value = 'dispute_channel'  ")
            .append("	left join  ")
            .append("	    conf.vwlookup dd on dd.keycode = d.dispute_status and dd.lookup_group_value = 'dispute_status'  ")
            .append(" WHERE (:clientId::integer is null or d.client_id = :clientId::integer) AND (:clientJobScheduleId::bigint is null OR acc.client_job_schedule_id = :clientJobScheduleId::bigint) AND coalesce(date(d.dtm_utc_create), current_date) >= coalesce(:placementDateFrom, date(d.dtm_utc_create), current_date)")
            .append(" AND coalesce(date(d.dtm_utc_create), current_date) <= coalesce(:placementDateTo, date(d.dtm_utc_create), current_date)  ")
            .append(" AND d.record_status_id = " + ConfRecordStatus.confRecordStatus.get(ConfRecordStatus.SUSPECTED).getRecordStatusId() + " ")
            .append(" ORDER BY d.dispute_id asc")
            .toString();

    public static final String CLIENT_ID_WHERE_CLAUSE = new StringBuffer()
            .append("		and acc.client_id = :clientId ")
            .toString();

    public static final String CLIENT_JOB_SCHEDULE_ID_WHERE_CLAUSE = new StringBuffer()
            .append("		and acc.client_job_schedule_id = :clientJobScheduleId ")
            .toString();

	public static final String GET_BANKRUPTCY_DETAIL = new StringBuffer()
            .append(" select b.bankruptcy_id bankruptcyId, b.client_bankruptcy_id clientBankruptcyId, b.client_account_number clientAccountNumber, ")
            .append(" b.client_id clientId, cl.full_name clientName, pa.partner_id partnerId, pa.full_name partnerName, ")
            .append(" b.account_Id accountId, b.bankruptcy_chapter bankruptcyChapter, bc.lookup_value bankruptcyChapterVal, b.dt_bankruptcy_filling dtBankruptcyFilling, ")
            .append(" b.dt_bankruptcy_report dtBankruptcyReport, b.bankruptcy_type bankruptcyType, bt.lookup_value bankruptcyTypeVal, ")
            .append(" b.channel, ch.lookup_value channelVal, b.mode_of_receipt modeOfReceipt, mor.lookup_value modeOfReceiptVal, ")
            .append(" b.bankruptcy_case_number bankruptcyCaseNumber, b.amt_total_bankruptcy amtTotalBankruptcy, b.amt_principal_bankruptcy amtPrincipalBankruptcy, ")
            .append(" b.amt_interest_bankruptcy amtInterestBankruptcy, b.amt_fee_amount_bankruptcy amtFeeAmountBankruptcy, b. bankruptcy_court_city bankruptcyCourtCity, ")
            .append(" b.bankruptcy_court_state bankruptcyCourtState, cs.full_name bankruptcyCourtStateVal, ")
            .append(" b.amt_balance_bankruptcy_filling amtBalanceBankruptcyFilling, b.amt_balance_bankruptcy_notified amtBalanceBankruptcyNotified, ")
            .append(" b.dt_claim_proof_due dtClaimProofDue, b. dt_claim_proof_filed dtClaimProofFiled, ")
            .append(" b.bankruptcy_petition_status bankruptcyPetitionStatus, bps.lookup_value bankruptcyPetitionStatusVal, ")
            .append(" b.bankruptcy_process_status bankruptcyProcessStatus, bpr.lookup_value bankruptcyProcessStatusVal, ")
            .append(" b.objection_status objectionStatus, os.lookup_value objectionStatusVal, ")
            .append(" b.automatic_stay_status automaticStayStatus, ass.lookup_value automaticStayStatusVal, ")
            .append(" b.client_attorney_id clientAttorneyId, b.equabli_attorney_id equabliAttorneyId, ")
            .append(" b.client_trustee_id clientTrusteeId, b.equabli_trustee_id equabliTrusteeId, concat(c.first_name, ' ', c.middle_name, ' ', c.last_name) consumerName, ")
            .append(" b.consumer_id consumerId, b.client_consumer_number clientConsumerNumber, b.dt_resolution resolutionDate ")
            .toString();

	public static final String GET_BANKRUPTCY_COUNT = new StringBuffer()
            .append(" select count(b.bankruptcy_id) over() ::integer recordcount, ")
            .append(" ceil((count(b.bankruptcy_id) over())*1.0/:pageSize) ::integer pagecount, :pageNumber pagenumber, :pageSize pagesize ")
            .toString();

	public static final String BANKRUPTCY_JOIN = new StringBuffer()
            .append(" from data.bankruptcy b ")
            .append(" left join data.account acc on acc.client_id = b.client_id and acc.client_account_number = b.client_account_number ")
            .append(" left join conf.client cl on b.client_id = cl.client_id ")
            .append(" left join conf.partner pa on acc.partner_id = pa.partner_id ")
            .append(" left join data.consumer c on b.consumer_id = c.consumer_id ")
            .append(" left join conf.vwlookup bc on bc.keycode = b.bankruptcy_chapter and bc.lookup_group_value = 'bankruptcy_chapter' ")
            .append(" left join conf.vwlookup bt on bt.keycode = b.bankruptcy_type and bt.lookup_group_value = 'bankruptcy_type' ")
            .append(" left join conf.vwlookup ch on ch.keycode = b.channel and ch.lookup_group_value = 'compliance_channel' ")
            .append(" left join conf.vwlookup mor on mor.keycode = b.mode_of_receipt and mor.lookup_group_value = 'compliance_mode' ")
            .append(" left join conf.country_state cs on lower(b.bankruptcy_court_state) = lower(cs.state_code) ")
            .append(" left join conf.vwlookup bps on bps.keycode = b.bankruptcy_petition_status and bps.lookup_group_value = 'bankruptcy_petition_status' ")
            .append(" left join conf.vwlookup bpr on bpr.keycode = b.bankruptcy_process_status and bpr.lookup_group_value = 'bankruptcy_process_status' ")
            .append(" left join conf.vwlookup os on os.keycode = b.objection_status and os.lookup_group_value = 'objection_status' ")
            .append(" left join conf.vwlookup ass on ass.keycode = b.automatic_stay_status and ass.lookup_group_value = 'automatic_stay_status' ")
            .toString();

	public static final String BANKRUPTCY_ID = new StringBuffer()
            .append(" where b.bankruptcy_id = :bankruptcyId ")
            .toString();

	public static final String LIMIT_QUERY = " limit coalesce(:pageSize, 1) offset (coalesce(:pageNumber, 1) -1) * coalesce(:pageSize, 1) ";
	
	public static final String GET_PARTNER_COMMISSION = new StringBuffer()
			.append("   ")
			.append("  select  ")
			.append("  	value.configured_value configuredValue  ")
			.append("  from  ")
			.append("  	conf.appconfig_value value  ")
			.append("  inner join  ")
			.append(" 	 conf.appconfig_name name on value.appconfig_name_id = name.appconfig_name_id ")
			.append("    where  ")
			.append("  	value.configured_for = 'CL' and value.client_id = :clientId and name.short_name = 'IS_COMMISION_CAL_REQ' ")
			.append("   ")
			.toString();
}